### ISSUE TITLE
localhost-componentlist.json and platform_cert.date.crt do not match

### ISSUE THREAD

**Issue by cyrus-dev** [nsacyber/paccor#44]
While investigating an issue related to the ACA, there as a mismatch for the platform information in the supply chain validator matching test.  Upon further investigation I noticed that the localhost-compenentlist.json and the platform_cert associated didn't have the same information for platform.  The platform information is missing from the certificate and just has "Not Specified".

However this is on in the **emulator** and not on the **host machine** in the same scenario.

**Comment by iadgovuser29** [comment]
Do you have an example file?
