### ISSUE TITLE
Add gradle wrapper checksum verification

### ISSUE THREAD

**Issue by salrashid123** [nsacyber/paccor#99]
Add steps/peoperty values to verify [gradlewrapper checksum](https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification)

the repo uses `gradle-4.5.1`

```bash
$ sha256sum gradle-wrapper.jar 
3bf04e39ed259ff0a1217a875199a11775855d2a29207b98318ac79178249de8  gradle-wrapper.jar


$ cd gradle/wrapper
$ curl -s --location --output gradle-wrapper.jar.sha256 \
   https://services.gradle.org/distributions/gradle-4.5.1-wrapper.jar.sha256
$ echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256

$ sha256sum --check gradle-wrapper.jar.sha256
```

**Comment by iadgovuser29** [comment]
I've tried to set this up using GitHub Actions: https://github.com/marketplace/actions/gradle-wrapper-validation

Are you saying that action wasn't set up properly?

**Comment by salrashid123** [comment]
Its setup correctly...but to me the validation an arms length away:

if i were to git clone this repo, i'd like to "see" all the components that went into it (eg, source, bash scripts, etc).  The gradle wrapper is the opaque one that i woudn't be able to readily verify on my own (since its done implictly via github).   it'd help with transparency if there was a line in the readme like "If you would like to verify the integrity of the gradle wrapper manually, see [Verifying the integrity of the Gradle Wrapper JAR](https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification)"

**Comment by iadgovuser29** [comment]
I already had a comment in the readme about validation of the jar using the github action. It's easy enough to add a link to perform local validation. Thanks for the suggestion.
